import './accordion';
import './deepl';
import './jeesl.imagewall';
import './jeesl.image360';
import './jeesl.slider';
import './jeesl';
import './preventMarkupPasting';
import './tab';
import hljs from 'highlight.js';
import 'bootstrap';
