alter table AomAsset add constraint UC_AomAsset_realm_code unique (realm_id, rref, code);
alter table AomAssetType add constraint UC_AomAssetType_realm_view_code unique (realm_id, rref, view_id, code);
alter table AomAssetTypeJtDescription add constraint UK_3vf21ew4njgel0mqkxon776hg unique (description_id);
alter table AomAssetTypeJtLang add constraint UK_ivagmlf79i0r0iu9pbv6xkuuy unique (lang_id);
alter table AomCompanyJtScope add constraint UKfg2dutnto5609n9g130obnhq2 unique (company_id, scope_id);
alter table AomEventJtAsset add constraint UKr1j8winj9xfsldsfnhy13axk2 unique (event_id, asset_id);
alter table AomView add constraint UC_AomView_realm_code unique (realm_id, rref, code);
alter table AomView add constraint UC_AomView_realm_tree unique (realm_id, rref, tree);
alter table AomViewJtDescription add constraint UK_gsf9gkcpxp4arutvn9ix47ifc unique (description_id);
alter table AomViewJtLang add constraint UK_41c1b4arm9nu4ptkytan70s2j unique (lang_id);
alter table AomAsset add constraint FK1nl00c1nf6caj9a6c9ofntxm4 foreign key (manufacturer_id) references AomCompany;
alter table AomAsset add constraint FKqlh5ltgka917al0jpk63cu22g foreign key (parent_id) references AomAsset;
alter table AomAsset add constraint FKeivhradv7adk2q16wgremcqlh foreign key (realm_id) references IoStatus;
alter table AomAsset add constraint FKowp3n1gs2ct3bk2gk6hawfgox foreign key (status_id) references IoStatus;
alter table AomAsset add constraint FK8pvri4o9v1n4rrj9lms6n21af foreign key (type1_id) references AomAssetType;
alter table AomAssetType add constraint FK1v10d02yjpmktos36bagh6v9m foreign key (graphic_id) references IoGraphic;
alter table AomAssetType add constraint FKgrug4l3tjlxbbpu7erxdftb2 foreign key (parent_id) references AomAssetType;
alter table AomAssetType add constraint FKlamuo930b9rye7k6301ymal95 foreign key (realm_id) references IoStatus;
alter table AomAssetType add constraint FKf9ruj77xpv0ifbxd8prmp400w foreign key (view_id) references AomView;
alter table AomAssetTypeJtDescription add constraint FKs021ycqndabjj5holjbk9t7o1 foreign key (description_id) references IoDescription;
alter table AomAssetTypeJtDescription add constraint FK9xywccht3o0rvd5p4xfd1gs4j foreign key (type_id) references AomAssetType;
alter table AomAssetTypeJtLang add constraint FKpgutd8krg8pv3mqimrp9m5u45 foreign key (lang_id) references IoLang;
alter table AomAssetTypeJtLang add constraint FK9vs2exsw2eloet6s6ma3vjhix foreign key (type_id) references AomAssetType;
alter table AomCompany add constraint FKbm6sbpr8fchwfy7j14vl1t7yr foreign key (realm_id) references IoStatus;
alter table AomCompanyJtScope add constraint FK8g5dfsilcr8ksbs98676lsbt2 foreign key (scope_id) references IoStatus;
alter table AomCompanyJtScope add constraint FKd2aps4bb8eits7qe7vvrqkogr foreign key (company_id) references AomCompany;
alter table AomEvent add constraint FKfitfyui7x99ade79sob91a8yw foreign key (company_id) references AomCompany;
alter table AomEvent add constraint FK6gnd727rprvra6uix12skh5p0 foreign key (frContainer_id) references IoFileContainer;
alter table AomEvent add constraint FKrgnmfa61ws6d4nrxkb5e7l80 foreign key (markup_id) references IoMarkup;
alter table AomEvent add constraint FKtdon57uolnup7s20jkirknrc foreign key (status_id) references IoStatus;
alter table AomEvent add constraint FKkhaofsii2qdrok3nggckrpmh7 foreign key (type_id) references IoStatus;
alter table AomEventJtAsset add constraint FK3y4qer0ut0bg3ccwy2km6orol foreign key (asset_id) references AomAsset;
alter table AomEventJtAsset add constraint FKq0ktq932x1su2wqest99yd5ru foreign key (event_id) references AomEvent;
alter table AomView add constraint FK860lh3vp0un3kcv9uf33l0ckm foreign key (graphic_id) references IoGraphic;
alter table AomView add constraint FKfeg5hfgpsv2jdxj0p05yo2xt3 foreign key (realm_id) references IoStatus;
alter table AomViewJtDescription add constraint FKlwdopw6kh2fh0ybcdtq6f4ymh foreign key (description_id) references IoDescription;
alter table AomViewJtDescription add constraint FKp3dxmuj5tckffjt57ya2o6qs7 foreign key (view_id) references AomView;
alter table AomViewJtLang add constraint FK6n3od9o2ugbibbwuekge953ju foreign key (lang_id) references IoLang;
alter table AomViewJtLang add constraint FKde9eklsphocdyhvqlp061epa5 foreign key (view_id) references AomView;
