alter table TenantStatus add constraint UKfrf1ccjmrwl4d7ohiv5n1n29l unique (type, realm_id, rref, code);
alter table TenantStatusJtDescription add constraint UK_dj045gofkujw367s0ray6dovs unique (description_id);
alter table TenantStatusJtLang add constraint UK_hsjvrvvtxjvgodswatp1jjukf unique (lang_id);
alter table TenantStatus add constraint FKbgu1pg3lp7ptca9pli0tuygtc foreign key (graphic_id) references IoGraphic;
alter table TenantStatus add constraint FKofovx4dwcihcvwrwhlnd3qs54 foreign key (parent_id) references TenantStatus;
alter table TenantStatus add constraint FKcfiu2btsvfv4y7ku404cb4i9u foreign key (realm_id) references IoStatus;
alter table TenantStatusJtDescription add constraint FKqwhcyg176ehoqsxejif3ickm1 foreign key (description_id) references IoDescription;
alter table TenantStatusJtDescription add constraint FK3ibcvq3ydgxlinsival44cux7 foreign key (status_id) references TenantStatus;
alter table TenantStatusJtLang add constraint FKhij6r79sdsonu6nam5g5ig9fi foreign key (lang_id) references IoLang;
alter table TenantStatusJtLang add constraint FK8gf6ct9w5uln3tu1rv3e95isd foreign key (status_id) references TenantStatus;