alter table IoFileMetaJtDescription add constraint UK_hu774vraqhpmoexnfsdakra5k unique (description_id);
alter table IoFileReplication add constraint UK37joqelw8sjrrhiefgfbsa1aa unique (storageSrc_id, storageDst_id);
alter table IoFileStorage add constraint UK3tupb03iuxgto7gtn4rvreai9 unique (code);
alter table IoFileStorageJtDescription add constraint UK_skyp6p5arg4hnn40gej8qlr41 unique (description_id);
alter table IoFileStorageJtLang add constraint UK_qse7q6kb8pj0b7enspj1fyig7 unique (lang_id);
alter table IoFileContainer add constraint FKhl3fbb2n4kaor2tlnuf4grat7 foreign key (storage_id) references IoFileStorage;
alter table IoFileMeta add constraint FK46q0m7tgaou6r5smfw6m51smb foreign key (container_id) references IoFileContainer;
alter table IoFileMeta add constraint FKk0x6hi1dyk9jggjnu3fj85deb foreign key (status_id) references IoStatus;
alter table IoFileMeta add constraint FKp5ef2ji24xa3owdbb4e1axypp foreign key (type_id) references IoStatus;
alter table IoFileMetaJtDescription add constraint FK3y2mlbiwqt1tdtacbfm908n1i foreign key (description_id) references IoDescription;
alter table IoFileMetaJtDescription add constraint FK3bkmv6v35car98veorxtxtwnc foreign key (meta_id) references IoFileMeta;
alter table IoFileReplication add constraint FK8ybxvwiiip5krgc8ml51njcq5 foreign key (storageDst_id) references IoFileStorage;
alter table IoFileReplication add constraint FKlks6i9b23xjhek4ac91rrh64a foreign key (storageSrc_id) references IoFileStorage;
alter table IoFileReplication add constraint FKhgg9cc962esaw68syig2b0hfe foreign key (type_id) references IoStatus;
alter table IoFileReplicationInfo add constraint FKa68xkj6a69y7st7bsamptl6w0 foreign key (meta_id) references IoFileMeta;
alter table IoFileReplicationInfo add constraint FKhaoet7rffcy23ol05p9hebdi1 foreign key (replication_id) references IoFileReplication;
alter table IoFileReplicationInfo add constraint FK2t5tk0mtwfpfnay7qm1taeli8 foreign key (status_id) references IoStatus;
alter table IoFileStorage add constraint FKl0quldd65ua6kdw7l8pryj9v0 foreign key (engine_id) references IoStatus;
alter table IoFileStorage add constraint FKi9aofycfuwu9do98ajh8nsewk foreign key (type_id) references IoStatus;
alter table IoFileStorageJtDescription add constraint FKdfh0j8uohcjtt18wtbxfwvahr foreign key (description_id) references IoDescription;
alter table IoFileStorageJtDescription add constraint FKc3u8fm7e48duy83d5u3ahpmtt foreign key (storage_id) references IoFileStorage;
alter table IoFileStorageJtLang add constraint FKtc1smfgsxw9q10qrgqob41mxq foreign key (lang_id) references IoLang;
alter table IoFileStorageJtLang add constraint FKnn97ukwydc983d66xvnrncs5l foreign key (storage_id) references IoFileStorage;