alter table IoMavenArtifactJtReason add constraint uk_IoMavenArtifactJtReason unique (artifact_id, reason_id);
alter table IoMavenDependency add constraint uk_IoMavenDependency_artifact_depends unique (artifact_id, dependsOn_id);
alter table IoMavenEeReferral add constraint uk_IoMavenEeReferral_edition_standard_recommendation unique (edition_id, standard_id, recommendation);
alter table IoMavenArtifact add constraint fk_IoMavenArtifact_group foreign key (group_id) references IoMavenGroup;
alter table IoMavenArtifact add constraint fk_IoMavenArtifact_replacedBy foreign key (replacedBy_id) references IoMavenArtifact;
alter table IoMavenArtifact add constraint fk_IoMavenArtifact_suitability foreign key (suitability_id) references IoStatus;
alter table IoMavenArtifactJtReason add constraint fk_IoMavenArtifactJtReason_reason foreign key (reason_id) references IoMavenArtifact;
alter table IoMavenArtifactJtReason add constraint fk_IoMavenArtifactJtReason_artifact foreign key (artifact_id) references IoMavenArtifact;
alter table IoMavenDependency add constraint fk_IoMavenDependency_artifact foreign key (artifact_id) references IoMavenVersion;
alter table IoMavenDependency add constraint fk_IoMavenDependency_dependsOn foreign key (dependsOn_id) references IoMavenVersion;
alter table IoMavenEeReferral add constraint fk_IoMavenEeReferral_artifiact foreign key (artifact_id) references IoMavenVersion;
alter table IoMavenEeReferral add constraint fk_IoMavenEeReferral_edition foreign key (edition_id) references IoStatus;
alter table IoMavenEeReferral add constraint fk_IoMavenEeReferral_standard foreign key (standard_id) references IoStatus;
alter table IoMavenModule add constraint FKc2fr7ii7117d094pbme9tgpjq foreign key (graphic_id) references IoGraphic;
alter table IoMavenModule add constraint fk_iomavenmodule_jdk foreign key (jdk_id) references IoStatus;
alter table IoMavenModule add constraint fk_IoMavenModule_parent foreign key (parent_id) references IoMavenModule;
alter table IoMavenModule add constraint fk_IoMavenModule_structure foreign key (structure_id) references IoStatus;
alter table IoMavenModule add constraint fk_IoMavenModule_type foreign key (type_id) references IoStatus;
alter table IoMavenModuleEe add constraint FKbbw7jj98vpgyid1sag1owotpl foreign key (ee_id) references IoStatus;
alter table IoMavenModuleEe add constraint FK9315pqk1eyopngcx146i0hwqt foreign key (module_id) references IoMavenModule;
alter table IoMavenUsage add constraint FKqwmtgv8tyr7k63sdf8u2b7xvr foreign key (module_id) references IoMavenModule;
alter table IoMavenUsage add constraint FKeuae28rup20d54r37gvuawh9e foreign key (version_id) references IoMavenVersion;
alter table IoMavenUsageJtScope add constraint FKogk8lt4tcbs0305vglhgmpwx4 foreign key (scope_id) references IoStatus;
alter table IoMavenUsageJtScope add constraint FKentl3c263stglsnhpr7hapqh foreign key (usage_id) references IoMavenUsage;
alter table IoMavenVersion add constraint fk_IoMavenVersion_artifact foreign key (artifact_id) references IoMavenArtifact;
alter table IoMavenVersion add constraint fk_IoMavenVersion_maintainer foreign key (maintainer_id) references IoStatus;
alter table IoMavenVersion add constraint fk_IoMavenVersion_outdate foreign key (outdate_id) references IoStatus;
alter table IoMavenVersion add constraint fk_iomavenmodule_jdk foreign key (jdk_id) references IoStatus;
