CKEDITOR.config.forcePasteAsPlainText = true;
CKEDITOR.config.pasteFromWordRemoveStyles = true;
CKEDITOR.config.pasteFromWordRemoveFontStyles = true;
CKEDITOR.config.enterMode = CKEDITOR.ENTER_P;
//CKEDITOR.config.extraPlugins = 'autogrow';
//CKEDITOR.config.autoGrow_minHeight = 100;
CKEDITOR.config.removePlugins = 'elementspath';
CKEDITOR.config.resize_enabled = false;
CKEDITOR.config.width = '100%';
CKEDITOR.addCss('.cke_editable { margin: 0; line-height: 1.3em; font-size: 11px; } @media (max-width: 768px) { .cke_editable { font-size: 13px } } .cke_editable p { margin: 0 !important; }');
CKEDITOR.config.toolbar = [['Bold', 'Italic','-', 'NumberedList', 'BulletedList','-','Subscript', 'Superscript']];