alter table IoDbMetaColumn add constraint UK5ljrc30hah9itol20mqkgnaq unique (table_id, code);
alter table IoDbMetaConstraint add constraint UKed8io78fc4ko3udiw73d8oyva unique (table_id, code);
alter table IoDbMetaSnapshot add constraint UK7sq9792i54lyg1j4pq4c508bq unique (system_id, record);
alter table IoDbMetaTable add constraint UKt41mwi71v74ks14ofa56knief unique (system_id, code);
alter table IoDbMetaUnique add constraint UKh4vw4hsri6cmj3q3nbvxb25lq unique (constraint_id, column_id);
alter table IoDbMetaColumn add constraint FKk7y96fswbprocbsbhvvv1n5nf foreign key (table_id) references IoDbMetaTable;
alter table IoDbMetaColumn add constraint FKnu4lcvwlrr5t27qn8a2bm4hos foreign key (type_id) references IoStatus;
alter table IoDbMetaConstraint add constraint FKkna9oqjwqwbror8brcfqqjvnw foreign key (columnLocal_id) references IoDbMetaColumn;
alter table IoDbMetaConstraint add constraint FKaq8yunsmqoaoxgu5w8ccr0k8p foreign key (columnRemote_id) references IoDbMetaColumn;
alter table IoDbMetaConstraint add constraint FKn9fmqg9f79wjqhfgvusi67s0w foreign key (table_id) references IoDbMetaTable;
alter table IoDbMetaConstraint add constraint FKj2k7xt84p91ad45ia1wbnqrhg foreign key (type_id) references IoStatus;
alter table IoDbMetaSnapshot add constraint FK1gqtkjd6nln8hcwpbsogr5om foreign key (system_id) references IoSsiSystem;
alter table IoDbMetaSnapshotJtColumn add constraint FKrlmc01oi5rcufmmcibr8pklnq foreign key (column_id) references IoDbMetaColumn;
alter table IoDbMetaSnapshotJtColumn add constraint FK7capi7c34mc92ofso2ylp5x3o foreign key (snapshot_id) references IoDbMetaSnapshot;
alter table IoDbMetaSnapshotJtConstraint add constraint FKpq6fvk6yjnv9sbml8qvl9t93h foreign key (constraint_id) references IoDbMetaConstraint;
alter table IoDbMetaSnapshotJtConstraint add constraint FKs7hbfl3tsaus1tedm3rd65d4a foreign key (snapshot_id) references IoDbMetaSnapshot;
alter table IoDbMetaSnapshotJtTable add constraint FKd5395u6i208baya79r3ym3u8u foreign key (snapshot_id) references IoDbMetaSnapshot;
alter table IoDbMetaSnapshotJtTable add constraint FKfiwqmib4do8hpa4bl09699oo3 foreign key (table_id) references IoDbMetaTable;
alter table IoDbMetaTable add constraint FK56e7tidumlmekxq5n38eyqrvd foreign key (system_id) references IoSsiSystem;
alter table IoDbMetaUnique add constraint FKab8wgjgmbxhyj1kfr0dmerdpd foreign key (column_id) references IoDbMetaColumn;
alter table IoDbMetaUnique add constraint FKn3d9mo0wgfkgwxpg79dw46a6u foreign key (constraint_id) references IoDbMetaConstraint;
