create sequence SecurityUser_id_seq start 1 increment 1;
create table SecurityAction (id  bigserial not null, code varchar(255), documentation boolean, position int4 not null, visible boolean not null, template_id int8, view_id int8, primary key (id));
create table SecurityActionJtDescription (action_id int8 not null, description_id int8 not null, primary key (action_id, description_id));
create table SecurityActionJtLang (action_id int8 not null, lang_id int8 not null, primary key (action_id, lang_id));
create table SecurityArea (id  bigserial not null, code varchar(255), position int4 not null, restricted boolean not null, visible boolean, view_id int8, primary key (id));
create table SecurityAreaJtDescription (area_id int8 not null, description_id int8 not null, primary key (area_id, description_id));
create table SecurityAreaJtLang (area_id int8 not null, lang_id int8 not null, primary key (area_id, lang_id));
create table SecurityCategory (id  bigserial not null, code varchar(255), documentation boolean, position int4 not null, type varchar(255), visible boolean not null, primary key (id));
create table SecurityCategoryJtDescription (category_id int8 not null, description_id int8 not null, primary key (category_id, description_id));
create table SecurityCategoryJtLang (category_id int8 not null, lang_id int8 not null, primary key (category_id, lang_id));
create table SecurityContext (id  bigserial not null, code varchar(255), contextId int8, emailAddress varchar(255), emailName varchar(255), linkImpressum varchar(255), pageBackground varchar(255), pageCss varchar(255), pageHeadline varchar(255), pageLogo varchar(255), pagePrefix varchar(255), pageTitle varchar(255), position int4 not null, serverName varchar(255), primary key (id));
create table SecurityContextJtDescription (context_id int8 not null, description_id int8 not null, primary key (context_id, description_id));
create table SecurityContextJtLang (context_id int8 not null, lang_id int8 not null, primary key (context_id, lang_id));
create table SecurityMenu (id  bigserial not null, position int4 not null, visible boolean, context_id int8, parent_id int8, view_id int8, primary key (id));
create table SecurityMenuJtLang (menu_id int8 not null, lang_id int8 not null, primary key (menu_id, lang_id));
create table SecurityRole (id  bigserial not null, code varchar(255), documentation boolean, position int4 not null, visible boolean not null, category_id int8, primary key (id));
create table SecurityRoleJtAction (action_id int8 not null, role_id int8 not null);
create table SecurityRoleJtDescription (role_id int8 not null, description_id int8 not null, primary key (role_id, description_id));
create table SecurityRoleJtLang (role_id int8 not null, lang_id int8 not null, primary key (role_id, lang_id));
create table SecurityRoleJtUsecase (usecase_id int8 not null, role_id int8 not null);
create table SecurityRoleJtView (view_id int8 not null, role_id int8 not null);
create table SecurityTemplate (id  bigserial not null, code varchar(255), documentation boolean not null, position int4 not null, visible boolean not null, category_id int8, primary key (id));
create table SecurityTemplateJtDescription (template_id int8 not null, description_id int8 not null, primary key (template_id, description_id));
create table SecurityTemplateJtLang (template_id int8 not null, lang_id int8 not null, primary key (template_id, lang_id));
create table SecurityUsecase (id  bigserial not null, code varchar(255), documentation boolean, position int4 not null, visible boolean not null, category_id int8, primary key (id));
create table SecurityUsecaseJtAction (action_id int8 not null, usecase_id int8 not null);
create table SecurityUsecaseJtDescription (usecase_id int8 not null, description_id int8 not null, primary key (usecase_id, description_id));
create table SecurityUsecaseJtLang (usecase_id int8 not null, lang_id int8 not null, primary key (usecase_id, lang_id));
create table SecurityUsecaseJtView (view_id int8 not null, usecase_id int8 not null);
create table SecurityUser (system varchar(32) not null, id int8 not null, email varchar(255), firstName varchar(255), lastName varchar(255), permitLogin boolean, pwd varchar(255), salt varchar(255), primary key (id));
create table SecurityView (id  bigserial not null, accessLogin boolean, accessPublic boolean, code varchar(255), documentation boolean, maintenance boolean, packageName varchar(255), position int4 not null, redirect boolean, urlBase varchar(255), urlMapping varchar(255), viewPattern varchar(255), visible boolean not null, category_id int8, primary key (id));
create table SecurityViewJtDescription (view_id int8 not null, description_id int8 not null, primary key (view_id, description_id));
create table SecurityViewJtLang (view_id int8 not null, lang_id int8 not null, primary key (view_id, lang_id));
alter table SecurityAction add constraint UK829ce5cvkihwq9e9gxskb5gno unique (code);
alter table SecurityActionJtDescription add constraint UK_chlyh57pce65hphy40knhse6j unique (description_id);
alter table SecurityActionJtLang add constraint UK_i4rx8qvh44dwsa4aj3epqrngi unique (lang_id);
alter table SecurityArea add constraint UKoesb5fqa7i83v62cvwuu0jnm0 unique (view_id, code);
alter table SecurityAreaJtDescription add constraint UK_ipexamwf8c3kchj71w49k54xy unique (description_id);
alter table SecurityAreaJtLang add constraint UK_jr4i4kv5damqghm5lpmxj8cvj unique (lang_id);
alter table SecurityCategory add constraint UK8d8cfhkrhvyygimcbj8d6txhp unique (type, code);
alter table SecurityCategoryJtDescription add constraint UK_fs7ol2vjrkjt289xnskvmalry unique (description_id);
alter table SecurityCategoryJtLang add constraint UK_9k8yhybl8et3f6nkcymed0g0x unique (lang_id);
alter table SecurityContext add constraint UK4a70dq26urfqotrekn6unmfkj unique (code);
alter table SecurityContextJtDescription add constraint UK_kg2h6ntnn9sf7b55qc5y4vtup unique (description_id);
alter table SecurityContextJtLang add constraint UK_11bvcw8ipsibhu5ey551lh7e9 unique (lang_id);
alter table SecurityMenu add constraint UK_SecurityMenu_context_view unique (context_id, view_id);
alter table SecurityMenuJtLang add constraint UK_svvmqhmu9awa45h9g4x7lobyi unique (lang_id);
alter table SecurityRole add constraint UKn7rptfw24qgvebhtjkvhkqc37 unique (code);
alter table SecurityRoleJtDescription add constraint UK_dmn1u4anlo6owvs7simpybdhq unique (description_id);
alter table SecurityRoleJtLang add constraint UK_ib49eonggvr9arthkskhy8rpr unique (lang_id);
alter table SecurityTemplate add constraint UKp8gyqfk1phtnp1xi5pa81mclg unique (code);
alter table SecurityTemplateJtDescription add constraint UK_i4da54m1rotuf9yuntechrtru unique (description_id);
alter table SecurityTemplateJtLang add constraint UK_fno2w18j8ihfavu10r6jbwn2w unique (lang_id);
alter table SecurityUsecase add constraint UKi81ap51plv4tp0lri93l2l9bt unique (code);
alter table SecurityUsecaseJtDescription add constraint UK_ahkbqpc804u3t3kv0yvqvy5xx unique (description_id);
alter table SecurityUsecaseJtLang add constraint UK_kln0u06gfcdpgs36usa1759uw unique (lang_id);
alter table SecurityUser add constraint UK_kkldrg9jqi256n89pv39tu7lq unique (email);
alter table SecurityView add constraint UKb9lt1du5j24vkqlso2bdymfqx unique (code);
alter table SecurityViewJtDescription add constraint UK_3auj697oh0xb7gqoise6bwo7j unique (description_id);
alter table SecurityViewJtLang add constraint UK_erfvtog87ex50d550qqq0nc6w unique (lang_id);
alter table SecurityAction add constraint FKpn402mb4h3h9sp44ek8ndxvsb foreign key (template_id) references SecurityTemplate;
alter table SecurityAction add constraint FKowl57sw7udaqhls5c5fe3sbd7 foreign key (view_id) references SecurityView;
alter table SecurityActionJtDescription add constraint FKouc4ifnlw7u2xpbyv9hrbnnk9 foreign key (description_id) references IoDescription;
alter table SecurityActionJtDescription add constraint FKcgd8vqeg8d0u8djm7p039iny6 foreign key (action_id) references SecurityAction;
alter table SecurityActionJtLang add constraint FK3fcqaidwhqwa97e7i0jrnc4ny foreign key (lang_id) references IoLang;
alter table SecurityActionJtLang add constraint FK67667o27xwtgnwetgcygjo42t foreign key (action_id) references SecurityAction;
alter table SecurityArea add constraint FK73ci5jvg04u58p7thy9p1eg0v foreign key (view_id) references SecurityView;
alter table SecurityAreaJtDescription add constraint FK66nqejpf4c1pkggfaljtphyeu foreign key (description_id) references IoDescription;
alter table SecurityAreaJtDescription add constraint FKbqrmi0dev5jge0lxha6c476j0 foreign key (area_id) references SecurityArea;
alter table SecurityAreaJtLang add constraint FKrpox9d3s3feexwo6uqqdkti04 foreign key (lang_id) references IoLang;
alter table SecurityAreaJtLang add constraint FKjw3vtiuxckc7etnmbpj0rqc2g foreign key (area_id) references SecurityArea;
alter table SecurityCategoryJtDescription add constraint FKemq5afaqcyno3t7gqh07982u7 foreign key (description_id) references IoDescription;
alter table SecurityCategoryJtDescription add constraint FK5xaje8qxe4q9fmswybef7um1o foreign key (category_id) references SecurityCategory;
alter table SecurityCategoryJtLang add constraint FK3amq69lpwonjd14p61l99airv foreign key (lang_id) references IoLang;
alter table SecurityCategoryJtLang add constraint FK1w2yjalffi0xg8cpgi953e28f foreign key (category_id) references SecurityCategory;
alter table SecurityContextJtDescription add constraint FKjvekbdb8nd6xhqn0pp7gyxq3k foreign key (description_id) references IoDescription;
alter table SecurityContextJtDescription add constraint FKj6pv833t8igoq99yghlc4gy47 foreign key (context_id) references SecurityContext;
alter table SecurityContextJtLang add constraint FKp0s7yfcjmornok7amqowvw1st foreign key (lang_id) references IoLang;
alter table SecurityContextJtLang add constraint FKj97cyaf9f8u85xe6sp67cq66q foreign key (context_id) references SecurityContext;
alter table SecurityMenu add constraint FK4m2e6erb5xvxjtxhmfbpfrxy0 foreign key (context_id) references SecurityContext;
alter table SecurityMenu add constraint FKlggf8p7jj3v32a7dqcaix9shx foreign key (parent_id) references SecurityMenu;
alter table SecurityMenu add constraint FKddvyvj29bmoluvm17x5xwhwxx foreign key (view_id) references SecurityView;
alter table SecurityMenuJtLang add constraint FKhac04hw17k94b9wgyk85rla2a foreign key (lang_id) references IoLang;
alter table SecurityMenuJtLang add constraint FK32c5uihtb8ix18y3xxn3w5p4e foreign key (menu_id) references SecurityMenu;
alter table SecurityRole add constraint FKl1t2ejdaqm30icvssnxu1179s foreign key (category_id) references SecurityCategory;
alter table SecurityRoleJtAction add constraint FKbhk0qmfxud83qh24mnim9konu foreign key (role_id) references SecurityRole;
alter table SecurityRoleJtAction add constraint FKegmlc9cdos3xymj1pch0yunqg foreign key (action_id) references SecurityAction;
alter table SecurityRoleJtDescription add constraint FK18tkhr9feno87x7lltwd2eouc foreign key (description_id) references IoDescription;
alter table SecurityRoleJtDescription add constraint FK6p3xtx9jk0kpudehil59v3wwb foreign key (role_id) references SecurityRole;
alter table SecurityRoleJtLang add constraint FK6eycoa61bwlcwj63qlx8wkidx foreign key (lang_id) references IoLang;
alter table SecurityRoleJtLang add constraint FKg79ye30si2kt7r44e78whg0oj foreign key (role_id) references SecurityRole;
alter table SecurityRoleJtUsecase add constraint FKcmvcd51w5i0r5888pgygw8om1 foreign key (role_id) references SecurityRole;
alter table SecurityRoleJtUsecase add constraint FKkeb4jo9yegnq9uou5rt0gwd0g foreign key (usecase_id) references SecurityUsecase;
alter table SecurityRoleJtView add constraint FK7lq2303ncmd0yap29qqr3myuw foreign key (role_id) references SecurityRole;
alter table SecurityRoleJtView add constraint FKpr54wchig9wis8tyt3l0n0a95 foreign key (view_id) references SecurityView;
alter table SecurityTemplate add constraint FKh4gi5cxndcm6xoodvmnn2ivak foreign key (category_id) references SecurityCategory;
alter table SecurityTemplateJtDescription add constraint FKe2w3yu1mcfttj0ca0wdsecjxl foreign key (description_id) references IoDescription;
alter table SecurityTemplateJtDescription add constraint FKj4bowe5ijfxsg27o3j49nyeh foreign key (template_id) references SecurityTemplate;
alter table SecurityTemplateJtLang add constraint FKlk94p7xm9mxq25q65d8yvuhjh foreign key (lang_id) references IoLang;
alter table SecurityTemplateJtLang add constraint FKt1xfqj2r259bft1xo54pwavv6 foreign key (template_id) references SecurityTemplate;
alter table SecurityUsecase add constraint FK1ml5rrne7ig14a4qc4qn6fyiq foreign key (category_id) references SecurityCategory;
alter table SecurityUsecaseJtAction add constraint FKpojdbbcrosv6vivst11unhval foreign key (usecase_id) references SecurityUsecase;
alter table SecurityUsecaseJtAction add constraint FK5my50lgo9jamngxabi5m4td9v foreign key (action_id) references SecurityAction;
alter table SecurityUsecaseJtDescription add constraint FKjklx533axy8eg17fs0fdwocw2 foreign key (description_id) references IoDescription;
alter table SecurityUsecaseJtDescription add constraint FKroed2wweq8h777518yadqv9q2 foreign key (usecase_id) references SecurityUsecase;
alter table SecurityUsecaseJtLang add constraint FKfipsnbrbuv2myv6y6il73jw3a foreign key (lang_id) references IoLang;
alter table SecurityUsecaseJtLang add constraint FKtm0u1j4ul05q4n4wnaav2ra8u foreign key (usecase_id) references SecurityUsecase;
alter table SecurityUsecaseJtView add constraint FKbnj1tcislwqg4a5bj9awpag1o foreign key (usecase_id) references SecurityUsecase;
alter table SecurityUsecaseJtView add constraint FK5fhbtdapxtyn1hm9dbqnoq39 foreign key (view_id) references SecurityView;
alter table SecurityView add constraint FKnc0p3d8d6p0cu643ey1yy4p23 foreign key (category_id) references SecurityCategory;
alter table SecurityViewJtDescription add constraint FK1qug8c6y54lh8haaj82hfwmyk foreign key (description_id) references IoDescription;
alter table SecurityViewJtDescription add constraint FKic8jkilpc7tfuigela71liwb1 foreign key (view_id) references SecurityView;
alter table SecurityViewJtLang add constraint FKer39qir2pfs8aj6k77luj1xwv foreign key (lang_id) references IoLang;
alter table SecurityViewJtLang add constraint FKfdguootw24mys4mx1vq5soryo foreign key (view_id) references SecurityView;