alter table IoCmsJtLang add constraint UK_s3ctsjjly4337qujwkofspaq2 unique (lang_id);
alter table IoLabelAttributeJtDescription add constraint UK_2l8iwmvr0tq9h0eqjcccy06rr unique (description_id);
alter table IoLabelAttributeJtLang add constraint UK_cqvltuxenpje970tjlc3n4d6e unique (lang_id);
alter table IoLabelDiagram add constraint UK1nrj703mg4o4c1hbs1ljr11hu unique (code);
alter table IoLabelDiagramJtDescription add constraint UK_ag47ji6s19up69g8oqe08yv17 unique (description_id);
alter table IoLabelDiagramJtLang add constraint UK_edma0my5tsgjygvr4fox2e18x unique (lang_id);
alter table IoLabelEntity add constraint UKgdxwb6nws0j7ld4jjkw73sw5p unique (code);
alter table IoLabelEntityJtAttribute add constraint UK_er0mi0uplavvycpay0l3dh6a6 unique (attribute_id);
alter table IoLabelEntityJtDescription add constraint UK_qrc7vmm6q45kkxyvyulre4b9r unique (description_id);
alter table IoLabelEntityJtLang add constraint UK_lbqjiwafmhhecik68h5tek9fo unique (lang_id);
alter table IoRevisionMappingEntity add constraint UKltb24byap0o0my71v5h9ds70n unique (entity_id, scope_id);
alter table IoRevisionScope add constraint UK21derexnc1lyy5kr94i2fqkvu unique (code);
alter table IoRevisionScopeJtAttribute add constraint UK_ct5xre1ux3lti9dp720hggmcd unique (attribute_id);
alter table IoRevisionScopeJtDescription add constraint UK_g6g5s2mopxyhwsm2fw70m0cb4 unique (description_id);
alter table IoRevisionScopeJtLang add constraint UK_9lipa42sxyitkwso5097js44h unique (lang_id);
alter table IoLabelAttribute add constraint FKjth42n3anilxsw58mwl7e34u3 foreign key (entity_id) references IoLabelEntity;
alter table IoLabelAttribute add constraint FK9ncjt1gax2c0521mcf6ltsteq foreign key (relation_id) references IoStatus;
alter table IoLabelAttribute add constraint FK362udl6dhx27fb7vj3mwgplci foreign key (type_id) references IoStatus;
alter table IoLabelAttributeJtDescription add constraint FKh236rqanqq7gs8xi7sfqocfc4 foreign key (description_id) references IoDescription;
alter table IoLabelAttributeJtDescription add constraint FKgn8vhs6b9l9mfa1pgumpnn3g0 foreign key (attribute_id) references IoLabelAttribute;
alter table IoLabelAttributeJtLang add constraint FK53m36mo853p9fgck1og77220 foreign key (lang_id) references IoLang;
alter table IoLabelAttributeJtLang add constraint FKby5r5xxjxnvlfga9liudhy2c3 foreign key (attribute_id) references IoLabelAttribute;
alter table IoLabelDiagram add constraint FKrqubwx3aeo76uw1kavaoxjvf6 foreign key (category_id) references IoStatus;
alter table IoLabelDiagramJtDescription add constraint FKin1bq6mismb9xjpqsrjhktk13 foreign key (description_id) references IoDescription;
alter table IoLabelDiagramJtDescription add constraint FKt26qaqf9dw3qrcoj6k92wqd2l foreign key (diagram_id) references IoLabelDiagram;
alter table IoLabelDiagramJtLang add constraint FK18grukkgja8ly7ew1qxihgeog foreign key (lang_id) references IoLang;
alter table IoLabelDiagramJtLang add constraint FK9kn86b57yvi28rcfd47ai0bx7 foreign key (diagram_id) references IoLabelDiagram;
alter table IoLabelEntity add constraint FK7phvkkkn6epu5a4jxqwxspe0e foreign key (category_id) references IoStatus;
alter table IoLabelEntity add constraint FK67cgihp52mj6ndnt6oj3k1818 foreign key (diagram_id) references IoLabelDiagram;
alter table IoLabelEntityJtAttribute add constraint FKn1jsutree8l1bg3gt52lg3u2t foreign key (attribute_id) references IoLabelAttribute;
alter table IoLabelEntityJtAttribute add constraint FKbu3wpw8o6wh5p2438c0bpc1ul foreign key (entity_id) references IoLabelEntity;
alter table IoLabelEntityJtDescription add constraint FK6ccj7dergd4ksifbvb7o2lk5b foreign key (description_id) references IoDescription;
alter table IoLabelEntityJtDescription add constraint FK7bg68mwkx3qjbi67pqfu74b61 foreign key (entity_id) references IoLabelEntity;
alter table IoLabelEntityJtLang add constraint FK9lapnesk8ry85e8qs4u24l88q foreign key (lang_id) references IoLang;
alter table IoLabelEntityJtLang add constraint FKa7laeph87dfco2oljqpehncyq foreign key (entity_id) references IoLabelEntity;
alter table IoRevisionMappingEntity add constraint FK30hgef1go5y9xcbmv28lae57e foreign key (entity_id) references IoLabelEntity;
alter table IoRevisionMappingEntity add constraint FKdjupw3u631m3p1m2awi8fptp3 foreign key (scope_id) references IoRevisionScope;
alter table IoRevisionMappingEntity add constraint FK3mpglv6cqgyc58y7o165ufce foreign key (type_id) references IoStatus;
alter table IoRevisionScope add constraint FKgt4pyp18p29tkc0oftm5xdlm7 foreign key (category_id) references IoStatus;
alter table IoRevisionScopeJtAttribute add constraint FKksmmd1xnftby4to883jl57ang foreign key (attribute_id) references IoLabelAttribute;
alter table IoRevisionScopeJtAttribute add constraint FKp3tgti4ktgoupatopsb1glxki foreign key (scope_id) references IoRevisionScope;
alter table IoRevisionScopeJtDescription add constraint FK44mie2003o8qysr901dlxmm22 foreign key (description_id) references IoDescription;
alter table IoRevisionScopeJtDescription add constraint FKpicu1eav77cka29x0th8getxa foreign key (scope_id) references IoRevisionScope;
alter table IoRevisionScopeJtLang add constraint FK3ad6hxyvbadi04oboorcovm01 foreign key (lang_id) references IoLang;
alter table IoRevisionScopeJtLang add constraint FKjl0ayawyj6xpaisor03v05x04 foreign key (scope_id) references IoRevisionScope;