alter table TsClass add constraint UK29a0ab9dvu9jgsqx5ajntryax unique (code);
alter table TsClassJtDescription add constraint UK_qm3npafrdacibmgn8m2jw5ob1 unique (descr);
alter table TsClassJtLang add constraint UK_7od9kbguyubqxi9juqtgwqs3s unique (lng);
alter table TsMultiPointJtDescription add constraint UK_4ra5ke7puglhof0ylnp0rsmn8 unique (dscr);
alter table TsMultiPointJtLang add constraint UK_nya1jls3oih8uo2e6yiv0ihwt unique (lng);
alter table TsScope add constraint UKtm2k1cjima7olatv0dp67or55 unique (code);
alter table TsScopeJtDescription add constraint UK_o42mtyk8pjjmdu3tid9jjojr6 unique (dscr);
alter table TsScopeJtLang add constraint UK_e747gh17yto7ejrxn13igtnn2 unique (lng);
alter table TsClass add constraint FKfyfyysms9gjfav32dxxkub8lt foreign key (category_id) references IoStatus;
alter table TsClassJtDescription add constraint FKjhb6y9c1mu2pak393lmvs0wat foreign key (descr) references IoDescription;
alter table TsClassJtDescription add constraint FKh90n6190090clfv6dtubpbmih foreign key (class) references TsClass;
alter table TsClassJtLang add constraint FK60hnxix73alg7prd7iwq2ewrf foreign key (lng) references IoLang;
alter table TsClassJtLang add constraint FK4apwx0n3i33aldjq8dsbc3og8 foreign key (class) references TsClass;
alter table TsMultiPoint add constraint FKru7xcmug2tb38jh74h5de3l1w foreign key (scope_id) references TsScope;
alter table TsMultiPoint add constraint FKmeit0247ink0g583wu2dxd5io foreign key (sld_id) references GeoSld;
alter table TsMultiPoint add constraint FKt45nng5238a831rolkyia8pct foreign key (unit_id) references IoStatus;
alter table TsMultiPointJtDescription add constraint FKcs3fkckj5v1mtp1t53hsy5jgs foreign key (dscr) references IoDescription;
alter table TsMultiPointJtDescription add constraint FKc4pipu7x9cm731je8sggfgjyi foreign key (mp) references TsMultiPoint;
alter table TsMultiPointJtLang add constraint FKfissqp1dqijgs4mwe2ch1uh1d foreign key (lng) references IoLang;
alter table TsMultiPointJtLang add constraint FK97yrhcbse67a8kwjt6qvouhhx foreign key (mp) references TsMultiPoint;
alter table TsScope add constraint FK3bghghucupsgbu6ujuitu05gf foreign key (category_id) references IoStatus;
alter table TsScope add constraint FKf7fe970jsh94f31e7kno9b49o foreign key (sld_id) references GeoSld;
alter table TsScope add constraint FK1s1kmpbwoidpo6ee621sc5jq0 foreign key (type_id) references IoStatus;
alter table TsScope add constraint FKjwt123mmufn8tw88c4wn1r3bd foreign key (unit_id) references IoStatus;
alter table TsScopeJtClass add constraint FKiw67ck1jmcdfaemlwb7iqgtaq foreign key (class) references TsClass;
alter table TsScopeJtClass add constraint FKj6f0uyhx36lxnm3qimtbe3fto foreign key (scope) references TsScope;
alter table TsScopeJtDescription add constraint FKlr7oi1malf8n63dddrkqio7vy foreign key (dscr) references IoDescription;
alter table TsScopeJtDescription add constraint FKkuvx7i7vn8uddifl34c2uqyby foreign key (scope) references TsScope;
alter table TsScopeJtInterval add constraint FKa2adqvo1tf67dy4ovpy891n8y foreign key (intervl) references IoStatus;
alter table TsScopeJtInterval add constraint FKpfnnrfu9kbow2mw8d0wp2bv7c foreign key (scope) references TsScope;
alter table TsScopeJtLang add constraint FK7qijiunspin64v87jb40hhrnm foreign key (lng) references IoLang;
alter table TsScopeJtLang add constraint FK9gemau2dd9laoxnpo11qy2kol foreign key (scope) references TsScope;