alter table SystemConstraint add constraint UKhvm69db650qqi1te3sl7uhmcq unique (scope_id, code);
alter table SystemConstraintAlgorithm add constraint UKc83hxpu56a7fsf082gmswpm32 unique (code);
alter table SystemConstraintAlgorithmJtDescription add constraint UK_dn83iuobnbb28q1sut6a4ljmn unique (description_id);
alter table SystemConstraintAlgorithmJtLang add constraint UK_5saunthsuwju47oescxt4d32v unique (lang_id);
alter table SystemConstraintJtDescription add constraint UK_28wrejtmsihdbo4lf2qxer8o8 unique (lang_id);
alter table SystemConstraintJtLang add constraint UK_jjroffkcfy6gryc3h5hf9pso3 unique (lang_id);
alter table SystemConstraintResolutionJtDescription add constraint UK_e7ddf0q7wrhwe6ldnejfsa8i2 unique (description_id);
alter table SystemConstraintResolutionJtLang add constraint UK_mjru2o2bn3exsemwxj845so4u unique (lang_id);
alter table SystemConstraintScopeJtDescription add constraint UK_o0lvprhqfcwey6k94nc4r7c7b unique (description_id);
alter table SystemConstraintScopeJtLang add constraint UK_ichkh7lfj6xmlrexupoovr7rj unique (lang_id);
alter table SystemConstraint add constraint FKkx4ra0msewrge4bymil81wfj7 foreign key (level_id) references IoStatus;
alter table SystemConstraint add constraint FKlmiu5919keed8f6ehjqgj1l69 foreign key (scope_id) references SystemConstraintScope;
alter table SystemConstraint add constraint FKd07kj0unaa894rdk1yghywknn foreign key (type_id) references IoStatus;
alter table SystemConstraintAlgorithm add constraint FKq7pxlgxi8uvuu90f1hbsnud3x foreign key (category_id) references IoStatus;
alter table SystemConstraintAlgorithmJtDescription add constraint FKenkfdfx8sel8dvt7egfdohs4g foreign key (description_id) references IoDescription;
alter table SystemConstraintAlgorithmJtDescription add constraint FKryh9whpwjsetetdewmv0nqu73 foreign key (algorithm_id) references SystemConstraintAlgorithm;
alter table SystemConstraintAlgorithmJtLang add constraint FKo8wukah8wl0v6q0yt8l3g46xa foreign key (lang_id) references IoLang;
alter table SystemConstraintAlgorithmJtLang add constraint FKmhf2rmk16x7oq0hak47v1sxto foreign key (algorithm_id) references SystemConstraintAlgorithm;
alter table SystemConstraintJtDescription add constraint FKtgs0vjqwvdt1mo6tb0if4ijqg foreign key (lang_id) references IoDescription;
alter table SystemConstraintJtDescription add constraint FKkg9uun7owlb1m2oe518eidtj0 foreign key (constraint_id) references SystemConstraint;
alter table SystemConstraintJtLang add constraint FKchypu67wqm8fio419b9t4ekec foreign key (lang_id) references IoLang;
alter table SystemConstraintJtLang add constraint FKehqc42w7d86wpxi3ovwtn6kpi foreign key (constraint_id) references SystemConstraint;
alter table SystemConstraintResolution add constraint FKem389c0xd4ettpig3b7ab29pt foreign key (constraint_id) references SystemConstraint;
alter table SystemConstraintResolution add constraint FKc8xtkc1gv7jm1cnv269nug9ta foreign key (type_id) references IoStatus;
alter table SystemConstraintResolutionJtDescription add constraint FKljkdr4jw1knuc8bcy9d061wu5 foreign key (description_id) references IoDescription;
alter table SystemConstraintResolutionJtDescription add constraint FK7t9hbibqbhapmda31t1q5g8m7 foreign key (resolution_id) references SystemConstraintResolution;
alter table SystemConstraintResolutionJtLang add constraint FK63v9to2qtjd86u4o0ysd1909s foreign key (lang_id) references IoLang;
alter table SystemConstraintResolutionJtLang add constraint FKavcinigc5gvqvryam745gchuy foreign key (resolution_id) references SystemConstraintResolution;
alter table SystemConstraintScope add constraint FKpq4qh729vhssvy1y11cydvyqc foreign key (category_id) references IoStatus;
alter table SystemConstraintScopeJtDescription add constraint FKsp1xws6jbpbpwm5k88vtbpf22 foreign key (description_id) references IoDescription;
alter table SystemConstraintScopeJtDescription add constraint FKal3crglhi6lhr1ew1fpqckjxi foreign key (scope_id) references SystemConstraintScope;
alter table SystemConstraintScopeJtLang add constraint FKgjlcda7vhd7yga4f8uggtc2ul foreign key (lang_id) references IoLang;
alter table SystemConstraintScopeJtLang add constraint FK8dfw5haw62e0892xxwq5pti4h foreign key (scope_id) references SystemConstraintScope;